package com.fyber.inneractive.sdk.network;

import com.dramawave.core.network.model.DeviceRemoveEvent;

/* renamed from: com.fyber.inneractive.sdk.network.u */
/* loaded from: classes3.dex */
public enum EnumC20456u {
    FIRST_OPENED(10),
    EVENT_READY_ON_CLIENT(41),
    VAST_EVENT_PLAYED_FOR_2_SECONDS(42),
    VAST_EVENT_COMPANION_CLICKED(43),
    VAST_MEDIA_LOAD_RETRY_ATTEMPTED(44),
    VAST_EVENT_DVC_DETECTED(47),
    VAST_EVENT_DVC_IMPRESSION(48),
    OMID_VAST_DETECTION(50),
    METRIC_MEASUREMENTS_EVENT(60),
    MRAID_VIDEO_DETECTED(61),
    VAST_COMPANION_LOADED(69),
    VAST_COMPANION_DISPLAYED(71),
    VAST_EVENT_COMPANION_FILTERED(72),
    NUMBER_OF_COMPANIONS(73),
    VAST_COMPANION_LOAD_ATTEMPT(74),
    VAST_DEFAULT_COMPANION_DISPLAYED(76),
    FMP_COMPANION_SUCCESSFULLY_SHOWN(77),
    VAST_EVENT_SP_DETECTED(97),
    VAST_EVENT_SP_IMPRESSION(98),
    VAST_EVENT_SP_LOADED(99),
    MRAID_CUSTOM_CLOSE_DETECTED(391),
    INTERSTITIAL_VIEW_TIME(392),
    FAIL_SAFE_ACTIVATED(393),
    USER_SKIP_ACTION_LATENCY(394),
    USER_CLOSE_ACTION_LATENCY(395),
    EXTERNAL_BROWSER_OPENED(602),
    IGNITE_FLOW_STORE_PAGE_OPENED(DeviceRemoveEvent.f44290c),
    IGNITE_FLOW_INSTALL_CLICKED(DeviceRemoveEvent.f44291d),
    IGNITE_FLOW_CANCEL_INSTALL_CLICKED(610),
    IGNITE_FLOW_INSTALL_DONE(611),
    IA_AMAZON_ID(669),
    SDK_BIDDING_METRICS(699),
    IA_PUBLISHER_REQUESTED_SHOW(804),
    IA_IAB_GDPR_TCF_PURPOSE_1_DISABLED(870),
    FYBER_REPORT_AD(899),
    FYBER_SUCCESS_CLICK(990),
    BANNER_RESIZE_EXPAND(993),
    NETWORK_REQUEST_PASSED_ALLOWED_TIME(994),
    CAUGHT_EXCEPTION(998),
    IA_UNCAUGHT_EXCEPTION(999);

    int val;

    EnumC20456u(int i10) {
        this.val = i10;
    }
}
