package com.fyber.inneractive.sdk.network;

import com.bytedance.sdk.openadsdk.TTAdConstant;
import com.tencent.rtmp.TXLiveConstants;
import com.vungle.ads.internal.protos.Sdk;
import java.util.HashMap;
import p797y0.EnumC28857d;

/* renamed from: com.fyber.inneractive.sdk.network.t */
/* loaded from: classes3.dex */
public enum EnumC20448t {
    VAST_ERROR_DVC_FAILURE(46),
    FMP_SDK_INIT_FAILED(62),
    VAST_COMPANION_FAILED_LOADING(70),
    VAST_COMPANION_INCOMPATIBLE_MIMETYPE(75),
    FMP_COMPANION_FAILED_LOADING(78),
    ERROR_STORE_PROMO_FAILURE(96),
    VAST_ERROR_INVALID_RESPONSE(301),
    VAST_ERROR_TOO_MANY_WRAPPERS(302),
    VAST_ERROR_NO_MEDIA_FILES(303),
    VAST_ERROR_NO_COMPATIBLE_MEDIA_FILE(Sdk.SDKError.Reason.AD_EXPIRED_VALUE),
    VAST_ERROR_PRE_BUFFER_TIMEOUT(306),
    VAST_ERROR_BUFFER_TIMEOUT(307),
    VAST_ERROR_FAILED_PLAYING_MEDIA_FILE(308),
    VAST_ERROR_FAILED_PLAYING_ALL_MEDIA_FILES(311),
    VAST_ERROR_UNSECURE_URL(312),
    MRAID_ERROR_UNSECURE_CONTENT(313),
    VPAID_ERROR_UNSECURE_CONTENT(Sdk.SDKError.Reason.LINK_COMMAND_OPEN_FAILED_VALUE),
    MRAID_VIDEO_HAS_NOT_STARTED_PLAYING_IN_A_TIMELY_FASHION(390),
    VAST_UNKNOWN_PLAYER_ERROR(399),
    NATIVE_ERROR_INVALID_NATIVE_RESPONSE(401),
    NATIVE_ERROR_MISSING_PUB_REQUIRED_FIELD(402),
    NATIVE_ERROR_MISMATCH_REQUIRED_ASSET_RESPONSE(404),
    NATIVE_ERROR_INVALID_REQUIRED_ASSET_DATA(405),
    NATIVE_ERROR_INVALID_OPTIONAL_ASSET_DATA(406),
    NATIVE_ERROR_INVALID_LINK_WEB_URL(407),
    NATIVE_ERROR_FAILED_LOAD_ASSET(TTAdConstant.IMAGE_LIST_SIZE_CODE),
    NATIVE_ERROR_MISMATCH_OPTIONAL_ASSET_RESPONSE(411),
    NATIVE_ERROR_MISSING_PROTOCOL_REQUIRED_FIELD(412),
    NATIVE_ERROR_RECEIVED_VIDEO_BUT_NOT_SUPPORTED(413),
    NATIVE_ERROR_NO_VALID_URLS_FOR_CLICK(414),
    NATIVE_ERROR_SOME_INVALID_URLS_FOR_PROCESSED_CLICK(TTAdConstant.VIDEO_COVER_URL_CODE),
    MRAID_AUTO_ACTION_DETECTED(501),
    INTERNAL_CONFIG_MISMATCH(601),
    FATAL_ADM_PARSING_ERROR(603),
    FATAL_ADM_MARKUP_FETCHING_ERROR(604),
    TOKEN_EXCEEDS_LIMIT(605),
    IGNITE_FLOW_MODE_NOT_COMPATIBLE(606),
    IGNITE_FLOW_FAILED_TO_START(607),
    IGNITE_FLOW_FAILED_TO_INSTALL_APP(612),
    IGNITE_FLOW_FAILED_TO_LOAD_WEBPAGE(613),
    FATAL_CONFIGURATION_ERROR(701),
    FATAL_FEATURES_CONFIG_ERROR(704),
    IA_AD_LOAD_FAILED(801),
    IA_AD_EXPIRED(802),
    IA_AD_DESTROYED_WITHOUT_SHOW(803),
    IA_AD_FAILURE_DATA(850),
    CLICK_PARSING_FAILURE(991),
    MISSMATCH_SPOTID(992),
    FAILED_DNS(995),
    FETCH_TOKEN_DV_ERROR(1000),
    DV_ERROR_PHASE(1001),
    ODT_ENCRYPTION_EXCEPTION(1100),
    ODT_RAW_ONE_DT_ERROR(1101),
    ODT_ONE_DT_PARSE_ERROR(1102),
    ODT_ONE_DT_AUTHENTICATION_ERROR(1103),
    ODT_ONE_DT_BROADCAST_ERROR(1104),
    ODT_ONE_DT_REQUEST_ERROR(TXLiveConstants.PUSH_WARNING_BEAUTYSURFACE_VIEW_INIT_FAIL),
    ODT_ONE_DT_GENERAL_ERROR(TXLiveConstants.PUSH_WARNING_VIDEO_ENCODE_BITRATE_OVERFLOW);

    private static final HashMap<Integer, EnumC20448t> sMap = new HashMap<>();
    int val;

    static {
        for (EnumC20448t enumC20448t : values()) {
            sMap.put(Integer.valueOf(enumC20448t.val), enumC20448t);
        }
    }

    /* renamed from: a */
    public static EnumC20448t m35800a(EnumC28857d enumC28857d) {
        return sMap.get(Integer.valueOf(enumC28857d.f125831a));
    }

    EnumC20448t(int i10) {
        this.val = i10;
    }
}
