package androidx.compose.material3;

import androidx.compose.material3.tokens.PaletteTokens;
import androidx.compose.p326ui.graphics.Color;
import kotlin.Metadata;

/* compiled from: TonalPalette.kt */
@Metadata(m51404d1 = {"\u0000\u0002\n\u0000¨\u0006\u0000"}, m51405d2 = {"material3_release"}, m51406k = 2, m51407mv = {1, 8, 0}, m51409xi = 48)
/* loaded from: classes8.dex */
public final class TonalPaletteKt {
    static {
        PaletteTokens paletteTokens = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens2 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens3 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens4 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens5 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens6 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens7 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens8 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens9 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens10 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens11 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens12 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens13 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens14 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens15 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens16 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens17 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens18 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens19 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens20 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens21 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens22 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens23 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens24 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens25 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens26 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens27 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens28 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens29 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens30 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens31 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens32 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens33 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens34 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens35 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens36 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens37 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens38 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens39 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens40 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens41 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens42 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens43 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens44 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens45 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens46 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens47 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens48 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens49 = PaletteTokens.f18433a;
        paletteTokens.getClass();
        PaletteTokens paletteTokens50 = PaletteTokens.f18433a;
        PaletteTokens paletteTokens51 = PaletteTokens.f18433a;
        paletteTokens51.getClass();
        PaletteTokens paletteTokens52 = PaletteTokens.f18433a;
        paletteTokens51.getClass();
        PaletteTokens paletteTokens53 = PaletteTokens.f18433a;
        paletteTokens51.getClass();
        PaletteTokens paletteTokens54 = PaletteTokens.f18433a;
        paletteTokens51.getClass();
        PaletteTokens paletteTokens55 = PaletteTokens.f18433a;
        paletteTokens51.getClass();
        PaletteTokens paletteTokens56 = PaletteTokens.f18433a;
        paletteTokens51.getClass();
        PaletteTokens paletteTokens57 = PaletteTokens.f18433a;
        paletteTokens51.getClass();
        PaletteTokens paletteTokens58 = PaletteTokens.f18433a;
        paletteTokens51.getClass();
        PaletteTokens paletteTokens59 = PaletteTokens.f18433a;
        paletteTokens51.getClass();
        PaletteTokens paletteTokens60 = PaletteTokens.f18433a;
        paletteTokens51.getClass();
        PaletteTokens paletteTokens61 = PaletteTokens.f18433a;
        paletteTokens51.getClass();
        PaletteTokens paletteTokens62 = PaletteTokens.f18433a;
        paletteTokens51.getClass();
        PaletteTokens paletteTokens63 = PaletteTokens.f18433a;
        paletteTokens51.getClass();
        PaletteTokens paletteTokens64 = PaletteTokens.f18433a;
        paletteTokens51.getClass();
        PaletteTokens paletteTokens65 = PaletteTokens.f18433a;
        paletteTokens51.getClass();
        PaletteTokens paletteTokens66 = PaletteTokens.f18433a;
        paletteTokens51.getClass();
        PaletteTokens paletteTokens67 = PaletteTokens.f18433a;
        paletteTokens51.getClass();
        PaletteTokens paletteTokens68 = PaletteTokens.f18433a;
        paletteTokens51.getClass();
        PaletteTokens paletteTokens69 = PaletteTokens.f18433a;
        paletteTokens51.getClass();
        PaletteTokens paletteTokens70 = PaletteTokens.f18433a;
        paletteTokens51.getClass();
        PaletteTokens paletteTokens71 = PaletteTokens.f18433a;
        paletteTokens51.getClass();
        PaletteTokens paletteTokens72 = PaletteTokens.f18433a;
        paletteTokens51.getClass();
        PaletteTokens paletteTokens73 = PaletteTokens.f18433a;
        paletteTokens51.getClass();
        PaletteTokens paletteTokens74 = PaletteTokens.f18433a;
        paletteTokens51.getClass();
        PaletteTokens paletteTokens75 = PaletteTokens.f18433a;
        paletteTokens51.getClass();
        PaletteTokens paletteTokens76 = PaletteTokens.f18433a;
        paletteTokens51.getClass();
        PaletteTokens paletteTokens77 = PaletteTokens.f18433a;
        paletteTokens51.getClass();
        PaletteTokens paletteTokens78 = PaletteTokens.f18433a;
        Color.Companion companion = Color.f20106b;
        companion.m54245getUnspecified0d7_KjU();
        companion.m54245getUnspecified0d7_KjU();
        companion.m54245getUnspecified0d7_KjU();
        companion.m54245getUnspecified0d7_KjU();
        companion.m54245getUnspecified0d7_KjU();
        companion.m54245getUnspecified0d7_KjU();
        companion.m54245getUnspecified0d7_KjU();
        companion.m54245getUnspecified0d7_KjU();
        companion.m54245getUnspecified0d7_KjU();
        companion.m54245getUnspecified0d7_KjU();
        companion.m54245getUnspecified0d7_KjU();
    }
}
